# Generated by Django 5.0.6 on 2024-07-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Senior Developer", "Senior Developer"),
                    ("Junior Developer", "Junior Developer"),
                    ("Manager", "Manager"),
                    ("Clerk", "Clerk"),
                    ("tester", "tester"),
                ],
                max_length=50,
            ),
        ),
    ]
